gravitee-io/release

release.json, upgrades/3.0.0/README.adoc
This is a breaking change for API customers
Closes gravitee-io/issues#2842
=> feat(policy): use new major version of the apiKey policy

release.json
If API is created with openAPI of Swagger, user can choose to configure a xml-validation policy.
Closes gravitee-io/issues#4294
=> feat(xml-validation): configure xml-validation policy on API creation

release.json
If API is created with openAPI of Swagger, user can choose to configure a json-validation policy.
Closes gravitee-io/issues#4293
=> feat(json-validation): configure json-validation policy on API creation

release.json
=> fix(ES reporter): do not index headers to avoid too many field error

upgrades/3.x/3.6.0/README.adoc
Fixes https://github.com/gravitee-io/issues/issues/4744
=> feat: auto-enable geoip and user_agent when elasticsearch > 7.x

release.json
=> fix: rest-to-soap do not override request path info

release.json
Closes gravitee-io/issues#5097
=> feat(reporter): Expose timestamp to JSON formatter so it gets includeExpose timestamp to JSON formatter so it gets included in File Reporter

release.json
=> chore: bump gravitee-cockpit-connectors-ws to 1.0.1

release.json
Closes gravitee-io/issues#5468
=> fix: Default Schema is now set to "public" for jdbc

release.json
Closes gravitee-io/issues#5503
=> fix: Default Schema is now set to public for jdbc

upgrades/3.x/3.9.0/README.adoc
Closes gravitee-io/issues#5711
=> doc: warn JDBC users to wait for 3.9.1

release.json
Related to gravitee-io/issues#5764
=> chore(version): bump gravitee-node version to 1.12.1-SNAPSHOT

upgrades/3.x/3.9.2/README.adoc, upgrades/3.x/README.adoc
=> chore: add note about AE connector into the APIM 3.9.2 migration guide

.circleci/config.yml
To avoid having a malformed JSON in `release.json` file I added a simple CI job to check the file is a valid JSON file.
Example: 
https://app.circleci.com/pipelines/github/gravitee-io/release/1740/workflows/0afa9ed0-95a0-47d4-a2fd-90610955e0d8
=> Check `release.json` validity in CI workflow

release.json
* gateway-api to 1.26.1-SNAPSHOT
* graviteeio-node to 1.16.0-SNAPSHOT
=> fix: bump versions for opentracing

release.json
https://github.com/gravitee-io/gravitee-policy-metrics-reporter/releases/tag/1.1.0
=> chore: bump policy-metrics-reporter to 1.1.0

release.json
https://github.com/gravitee-io/issues/issues/5972
=> chore: bump policy-callout-http to 1.14.0

release.json
=> chore: bump policy-groovy to 1.16.0-SNAPSHOT

release.json
=> fix: bump gravitee-expression-language to 1.6.1

upgrades/3.x/3.10.1/README.adoc, upgrades/3.x/3.9.4/README.adoc, upgrades/3.x/README.adoc
and removing 3.12.0 link since it should be displayed only after the release
gravitee-io/issues#6029
=> Adding missing documentation

release.json
⚠️ Wait for official release of the plugins before merging this PR ⚠️ 
gravitee-io/issues#6176
=> fix: bump versions of resource-oauth2-providers-xxx

upgrades/3.x/README.adoc
⚠️ Wait for the 3.12.0 to be released before rebasing and merging this PR ⚠️ 
gravitee-io/issues#6029
=> adding link to 3.12.0 upgrade guide

release.json
Closes gravitee-io/issues#6205
=> fix: bump gravitee-gateway-api to 1.27.2-SNAPSHOT

upgrades/3.x/3.5.21/README.adoc, upgrades/3.x/README.adoc
⚠️ Wait for the 3.5.21 release before merging this PR ⚠️ 
gravitee-io/issues#6424
=> doc: add breaking change info about UIs migration into monorepo - 3.5.x

upgrades/3.x/3.10.4/README.adoc, upgrades/3.x/README.adoc
⚠️ Wait for the 3.10.4 release before merging this PR ⚠️
gravitee-io/issues#6425
=> doc: add breaking change info about UIs migration into monorepo - 3.10.x

release.json
:warning: don't merge before the release :warning: 
https://github.com/gravitee-io/issues/issues/6507
fix: bump gravitee-elasticsearch to 3.5.5-SNAPSHOT fixes ILM managed indexes on elastic reporter
=> fix: bump gravitee-elasticsearch to 3.5.5-SNAPSHOT fixes ILM managed indexes on elastic reporter

release.json
* Prepares the 3.10.8 release by changing the version of `gravitee-api-management`.
* Removes "SNAPSHOT" from the `gravitee-gateway-api` since it has been released in a standalone way.
=> Update release.json 3.10.x

release.json
https://github.com/gravitee-io/issues/issues/6423
:warning: Merge only before release :warning:
=> feat: bump gravitee-elasticsearch to 3.10.0 adds opensearch support

release.json
=> chore: bump jaeger tracer plugin to 1.0.1 version

upgrades/3.x/3.12.5/README.adoc, upgrades/3.x/README.adoc
Zip files and folders have been renamed
gravitee-io/issues#6635
⚠️ wait for the 3.12.5 to be released before merging this PR ⚠️
=> doc: gateway has been merged in APIM monorepo

release.json
:warning: merge only before releasing :warning: 
**Issue**
https://github.com/gravitee-io/issues/issues/6710
This backports in 3.10 : #6683
=> feat: bump elasticsearch to 3.8.2 changes ES reporter default plugins management

release.json
**Issue**
https://github.com/gravitee-io/issues/issues/6676
Bump cockpit connector ws to 2.0.1 to fix issue with sharding tags: https://github.com/gravitee-io/gravitee-cockpit-connectors/commit/1172010abab3c5e746809ca51181dff54fac2a46
=> Bump cockpit connector ws to 2.0.1

upgrades/3.x/3.10.9/README.adoc, upgrades/3.x/README.adoc
**Issue**
https://github.com/gravitee-io/issues/issues/6710
This backports in 3.10 : #6683
⚠️ merge only after releasing 3.10.9 ⚠️
=> docs: add 3.10.9 upgrade note about ElasticSearch reporter plugins configuration change

upgrades/3.x/3.14.0/README.adoc, upgrades/3.x/README.adoc
https://github.com/gravitee-io/issues/issues/6811
:warning: Please don't merge before 3.14 release :warning: 
add 3.14 upgrade note for bridge gateways upgrade order
=> docs: add 3.14 upgrade note for bridge gateways upgrade order

release.json
Update `gravitee-cockpit-connectors-ws` to 2.3.0. 
It looks strange to still be on 2.0.0 thought 🤔
=> chore: update cockpit-connectors-ws to 2.3.0

release.json
:warning: Merge during APIM 3.5.x release :warning: 
https://github.com/gravitee-io/issues/issues/6889
This backports https://github.com/gravitee-io/issues/issues/6423 to 3.5
=> feat: bump elasticsearch version to 3.5.6 adds openSearch support

release.json
As policies are now using semantic release version 1.7.0 has already been released so we can use it directly
=> chore: use stable version of gravitee-policy-json-to-json

release.json
=> fix(metrics): Add support for old prometheus label names for backward compatibility

release.json
https://github.com/gravitee-io/issues/issues/7194
=> chore: bump version of metrics-reporter policy to 1.2.1

release.json
=> fix: let the API Owner choose the Accept-Encoding

release.json
https://github.com/gravitee-io/issues/issues/7276
=> chore: bump ssl-enforcement policy to 1.2.1

upgrades/3.x/3.17.0/README.adoc, upgrades/3.x/README.adoc
https://github.com/gravitee-io/issues/issues/6224
Need to discuss if we remove `swagger.json` directly in this version or not ?
=> docs: migrate swagger v2 to openapi v3

release.json
gravitee-io/issues#7259
⚠️ We must keep bundled plugins in the `components` array since it is used by the packaging script.
=> Clean release.json thanks to semantic release

release.json
https://github.com/gravitee-io/issues/issues/6454
=> chore: bump resource-oauth2-provider-am to 1.14.2

.circleci/config.yml
This PR is created in the purpose of replacing the secrethub commands with the keeper commands, and adding the keeper orb, so that all new version of the gravitee orb can be used,
CircleCI dry_release_process : https://app.circleci.com/pipelines/github/gravitee-io/release/3197/workflows/37c2a433-a050-48e9-addc-591c6362716a
N.B : the dry release process will only test the secret commands launched inside of this workflow (ksm secret notation commands)
this job inside of the gravitee orb will fetch secrets only on non dry run mode :
nexus_staging_prepare_bucket
=> ci: secrethub to keeper

release.json
=> chore: bump gravitee-elasticsearch to 3.8.4-SNAPSHOT

release.json
`gravitee-resource-oauth2-provider-keycloak` was in this file only for building purposes and standalone release as it is not included in the APIM bundle, see: https://github.com/gravitee-io/jenkins-scripts/blob/master/src/main/python/package_bundles.py#L56
=> Remove `gravitee-resource-oauth2-provider-keycloak`

release.json
=> Adapt release.json with gravitee-elasticsearch split

release.json
=> Adapt release.json with gravitee-elasticsearch split - 3.5.x

release.json
=> Adapt release.json with gravitee-elasticsearch split - 3.10.x

release.json
=> Adapt release.json with gravitee-elasticsearch split - 3.16.x

release.json
**Issue**
gravitee-io/issues#7110
use latest version of gravitee-reporter-elasticsearch for ILM support
+
some simplification for the `release.json` file
=> use latest version of gravitee-reporter-elasticsearch for ILM support

release.json
**Issue**
gravitee-io/issues#7110
use latest version of gravitee-reporter-elasticsearch for ILM support
+
some simplification for the `release.json` file
=> use latest version of gravitee-reporter-elasticsearch for ILM support - 3.15.x

release.json
bump `gravitee-resource-oauth2-provider-generic`
gravitee-io/issues#7258
=> fix: bump gravitee-resource-oauth2-provider-generic

release.json
=> chore: bump connector-http to 1.1.9
