gravitee-io/release

upgrades/1.0.0/README.adoc
upgrades/1.0.0/mongodb/1-copy-members-to-memberships.js
upgrades/1.0.0/mongodb/2-remove-members.js
upgrades/README.adoc

feat(membership): store memberships in a dedicated repository

---

upgrades/1.4.0/README.adoc
upgrades/1.4.0/mongodb/1-update-application.js
upgrades/1.4.0/mongodb/2-create-archived-app.js
upgrades/README.adoc

fix(application): archive an application

---

upgrades/1.4.0/README.adoc
upgrades/1.4.0/mongodb/2-create-archived-app.js

fix(application): add default PO for archived application (#62)

---

upgrades/1.5.0/README.adoc
upgrades/1.5.0/mongodb/1-remove-event-picture.js
upgrades/README.adoc

fix(1.5.0): Add script to clean useless data

---

upgrades/1.8.0/README.adoc
upgrades/1.8.0/mongodb/1-convert-roles.js
upgrades/README.adoc

feat(roles): implementation of custom roles

---

upgrades/1.9.0/README.adoc
upgrades/1.9.0/mongodb/1-convert-groups.js
upgrades/1.9.0/mongodb/2-remove-old-attributes.js
upgrades/README.adoc

feat(groups): create default group for api and apps

---

upgrades/1.8.0/mongodb/1-convert-roles.js
upgrades/1.9.0/mongodb/1-convert-groups.js

fix(mongo): Database update scripts should be idempotent

---

upgrades/1.13.0/README.adoc

This closes gravitee-io/issues#160

feat: allows to configure specific CORS headers

---

upgrades/1.13.0/README.adoc

fix(cors): wrong default CORS configuration

---

upgrades/1.14.0/README.adoc
upgrades/1.14.0/mongodb/2-init-email-notifications.js

feat(notifications): add user notifications

---

upgrades/1.14.3/README.adoc
upgrades/README.adoc

This closes gravitee-io/issues#1148

fix: Allows to configure the brand of the portal title

---

upgrades/1.21.0/README.adoc

I think the point wasn't clear enough. It took us some time to get it :(

Clarified release notes for version 1.21

---

upgrades/1.23.0/README.adoc
upgrades/README.adoc

This closes gravitee-io/issues#1818

feat: Invite a user in a group

---

release.json

feat(fetcher): backport the github fetcher

---

upgrades/1.24.0/README.adoc
upgrades/README.adoc

This closes gravitee-io/issues#1505

feat: User creation from management gui / management API

---

upgrades/1.24.0/README.adoc

feat(ldap): add new configuration to search for users

---

release.iml
upgrades/1.25.0/README.adoc
upgrades/1.25.0/mongodb/1-applications-migration.js
upgrades/README.adoc

Closes gravitee-io/issues#1580

feat(dcr): Add Dynamic Client Registration support

---

upgrades/1.26.0/README.adoc
upgrades/1.26.0/mongodb/1-apis-migration.js
upgrades/README.adoc

This closes gravitee-io/issues#1996

feat: lifecycle API and review workflow

---

upgrades/1.25.0/README.adoc
upgrades/1.25.0/mongodb/2-users-archived-upgrade.js

fix(users): update the sourceId of archived users

---

upgrades/3.0.0/README.adoc
upgrades/3.0.0/mongodb/3-replace-apiArray-by-unique-api.js
upgrades/README.adoc

Closes gravitee-io/issues#2283

feat(plan): plan is now linked to one and only one api

---

upgrades/1.25.0/mongodb/1-applications-migration.js

Closes gravitee-io/issues#2331

fix for issue #2231

---

upgrades/3.0.0/mongodb/2-id-migration.js

fix(env): remove invalid characters

---

release.json

feat(services): Add a user-agent header for all services requests

---

release.json

feat(resource-filtering): bump to 1.5.1

---

upgrades/3.0.0/README.adoc
upgrades/3.0.0/mongodb/1-collections-linked-to-environment.js
upgrades/3.0.0/mongodb/2-id-migration.js

Closes gravitee-io/issues#3182

feat(multi-env): add organization feature

---

upgrades/1.25.23/README.adoc
upgrades/1.25.23/mongodb/1-memberships-archived-apps-migration.js
upgrades/README.adoc

Closes gravitee-io/issues#3273

fix: Some users are wrongly flagged as primary owners

---

upgrades/3.x/3.0.0/README.adoc

Closes gravitee-io/issues#3193

feat(management): remove legacy portal

---

upgrades/3.x/3.0.0/README.adoc
upgrades/3.x/3.0.0/mongodb/4-remove-devMode.js

Closes gravitee-io/issues#3439

feat(portal): remove dev mode

---

upgrades/3.x/3.0.0/mongodb/2-roles-groups-and-memberships-migration.js

fix(release): improve migration scripts

---

release.json

Closes gravitee-io/issues#2634

feat(gateway): new version of gravitee-definition for encodeURI removing

---

upgrades/3.x/3.0.0/mongodb/1-collections-linked-to-environment-or-organization.js
upgrades/3.x/3.0.0/mongodb/2-roles-groups-and-memberships-migration.js
upgrades/3.x/3.0.0/mongodb/3-replace-apiArray-by-unique-api.js

fix(multi-env): delete old indexes and creates new

---

release.json

Closes gravitee-io/issues#3689

Merge 1.25.25

---

upgrades/3.x/3.0.0/README.adoc
upgrades/README.adoc

fix(release): add explanation for new scopes and role mappings upgrade

---

upgrades/3.x/3.0.0/README.adoc
upgrades/3.x/3.0.0/mongodb/5-remove-orphan-documentation-pages.js

fix(release): add a script to remove orphan documentation pages

---

upgrades/3.x/3.0.0/README.adoc
upgrades/3.x/3.0.0/mongodb/6-remove-ALL-view-and-defaultView-field.js

Closes gravitee-io/issues#3767

feat(management): remove Default view ALL and 'default' field

---

upgrades/3.x/3.0.2/README.adoc
upgrades/3.x/3.0.2/mongodb/1-rename-view-in-category.js
upgrades/3.x/README.adoc

fix(): rename view in category

---

upgrades/3.x/3.1.0/README.adoc
upgrades/3.x/README.adoc

Closes gravitee-io/issues#4094

docker: Use non-root ports to run nginx

---

upgrades/3.x/3.0.7/README.adoc
upgrades/3.x/README.adoc

Closes gravitee-io/issues#4144

feat(management): remove portalURL config from gravitee.yml

---

release.json

feat: auto fetch pages based on user configuration

---

upgrades/3.x/3.2.0/README.adoc
upgrades/3.x/README.adoc

Closes gravitee-io/gravitee-cockpit#64

doc(ui-components): add breaking changes on gv-link css variables

---

release.json

fix(policy) : update version of policy callout-http

---

upgrades/3.x/3.0.0/README.adoc

Closes gravitee-io/issues#4335

docs(): add precision on mongo minimum version

---

upgrades/3.x/3.0.0/mongodb/2-roles-groups-and-memberships-migration.js

fix(memberships): duplicate memberships after the 3.0.0 migration

---

upgrades/3.x/3.3.0/README.adoc

Closes gravitee-io/issues#4376

fix(management): avoid breaking changes. Deprecates resources instead

---

release.json

feat(policy): #4296 addition of spike arrest policy

---

release.json

feat: update release.json for #4123

---

upgrades/3.x/3.3.0/README.adoc
upgrades/3.x/3.3.0/mongodb/2-update-json-validation-policy-scopes.js

fix(json-validation): update apis definition for json-validation policy

---

release.json

Closes gravitee-io/issues#4295

feat(management): upgrade gravitee-definition version

---

release.json

feat(management): addition of workflow audit event

---

release.json
upgrades/1.30.24/README.adoc
upgrades/README.adoc

feat(policy/resource-filtering): return 405 if method doesn't match

---

release.json

fix(policy/http-callout): addition of the useSystemProxy config

---

release.json

feat(mgnt): update repository dependency

---

release.json

fix(cache): set policy-cache version to 1.7.1

---

release.json

Fixes https://github.com/gravitee-io/issues/issues/4434

feat: forward x-forwarded-prefix to the backend endpoint

---

release.json

Closes gravitee-io/issues#4431

feat(processor): adapt policies and gateway version

---

release.json

Closes gravitee-io/issues#4297

feat(notification): manage notif template in database

---

upgrades/3.x/3.4.0/README.adoc
upgrades/3.x/3.4.0/mongodb/2-update-default-role-REVIEWER.js

Closes gravitee-io/issues#4436

feat(management): add permissions to REVIEWER role

---

upgrades/3.x/3.5.0/README.adoc
upgrades/3.x/3.5.0/mongodb/1-duplicate-some-parameters-for-console.js

upgrade script to duplicate some keys for console
Closes gravitee-io/issues#4642

feat(): manage Org & Env in parameters

---

release.json

Fixes https://github.com/gravitee-io/issues/issues/4589

feat: allow to migrate from policy studio v1 to v2

---

release.json

Closes gravitee-io/issues#4802

add retry policy

---

release.json

fix(policy callout): make variabled optional

---

release.json

Fixes https://github.com/gravitee-io/issues/issues/4679

fix: backport 4678

---

release.json

Fixes https://github.com/gravitee-io/issues/issues/4679

fix: typo from backport 4678

---

release.json

Closes gravitee-io/issues#4832

chore: Upgrade AM Resource plugin

---

release.json

fix(management): addition of findByEmail method in UserRepository

---

release.json

fix(repository-jdbc): fix search pages when criteria is null or empty

---

upgrades/3.x/3.4.0/mongodb/1-update-audit-to-replace-PORTAL-with_ORGANIZATION-and-ENVIRONMENT.js

Closes gravitee-io/issues#4881

feat(): improve migration script

---

release.json

Fixes https://github.com/gravitee-io/issues/issues/4747

feat: console dashboard page

---

release.json
upgrades/3.x/3.4.0/README.adoc
upgrades/3.x/3.5.0/README.adoc
upgrades/3.x/3.5.2/README.adoc
upgrades/3.x/3.5.2/mongodb/1-add-DEFAULT-referenceId-in-memberships.js

fix: social authentication is not working anymore

---

release.json

feat: allows to transform a JSON to a XML

---

release.json

Closes gravitee-io/issues#4769

feat(assign-metrics): use custom metrics

---

upgrades/3.x/3.6.0/README.adoc

Closes https://github.com/gravitee-io/issues/issues/4981

Add new configuration keys : Console UI and API urls

---

release.json

Closes gravitee-io/issues#4813

APIM: Add HTTP Signature policy

---

release.json

Closes gravitee-io/issues#5072

fix(dictionary): Add new tests for dictionary, property's keys containing a dot (.)

---

release.json

feat(management): add data logging masking policy

---

release.json

build: update release.json

---

release.json

feat: add a cache at the policy level

---

release.json

Closes gravitee-io/issues#5133

feat(management): Manage API PO in a group

---

release.json

feat(cache): Support of cache replication across an APIM cluster

---

release.json

Closes gravitee-io/issues#5126

chore: Remove useless dependencies

---

mongo-upgrade-template.js
release.json
upgrades/3.x/3.7.0/README.adoc
upgrades/3.x/3.7.0/mongodb/1-rename-collections-with-prefix.js

feat: allows to define a prefix for collections / tables

---

release.json

fix(repository): fully update an organization

---

release.json

Fixes https://github.com/gravitee-io/issues/issues/5236

feat: allow to filter probes on health resource

---

release.json

Closes gravitee-io/issues#5268

feat(gateway): Provide a way to retrieve an endpoint reference

---

release.json

Fixes https://github.com/gravitee-io/issues/issues/4893

feat: setting to make portal pages non-visible for anonymous user

---

release.json

Fixes https://github.com/gravitee-io/issues/issues/4903

feat: resource information in health API

---

release.json

Fixes https://github.com/gravitee-io/issues/issues/5186

feat: traffic shadowing

---

release.json

feat(portal): allows to change favicon

---

release.json

related to gravitee-io/issues#5338

fix: change the ratelimit policy version

---

release.json

Fixes https://github.com/gravitee-io/issues/issues/5354

fix: rollback to graviteepolicy-oauth2-1.15.0

---

upgrades/3.x/3.8.0/README.adoc
upgrades/3.x/3.8.0/mongodb/1-page-acl-migration.js

feat: add ACL on custom link

---

release.json

Closes gravitee-io/issues#5422

chore: Upgrade Cockpit WS connector to 1.3.0

---

release.json

chore(management): upgrade traffic shadowing policy

---

release.json

chore(management): upgrade keyless & groovy policies

---

release.json

fix(managment: API Analytics response payload not displayed

---

release.json

fix gravitee-io/issues#5421
fix gravitee-io/issues#5416

fix: backport #5416

---

upgrades/3.x/3.9.0/README.adoc
upgrades/3.x/3.9.0/mongodb/1-tags-tenants-and-entrypoints-migration.js

feat: associate sharding tags and tenants to organization

---

upgrades/3.x/3.9.0/mongodb/2-events-migration.js

Fixes https://github.com/gravitee-io/issues/issues/5357

feat: allow to associate a gateway to environments

---

release.json

Closes gravitee-io/issues#5298

feat(management): allow to filter by context-path

---

upgrades/3.x/3.5.11/README.adoc

feat(management): add breaking changes info

---

upgrades/3.x/3.9.0/README.adoc

Closes gravitee-io/issues#5523

chore: Add a section about memory management

---

release.json

feat(notification): allow to notify during certain periods of time

---

upgrades/3.x/3.9.0/README.adoc

Closes gravitee-io/issues#4475

feat(management): cleanup APIM swagger.json

---

release.json

Closes gravitee-io/issues#5545

chore: upgrade to latest version

---

release.json

feat(management): platform policies

---

upgrades/3.x/3.5.0/README.adoc
upgrades/3.x/3.5.14/1-fix-cors-env-vars.js
upgrades/3.x/3.5.14/README.adoc

fix(management): clean CORS env vars & migration guide

---

release.json

feat: allow to use EL in health check configuration

---

release.json

Closes gravitee-io/issues#5668

fix(monitor): report node monitor only and avoid npe

---

release.json

Closes gravitee-io/issues#5673

fix(audit): add api-review events in audit event list

---

release.json

fix(cache): properly create and destroy cache on api deployment 

---

release.json

Related to gravitee-io/issues#5580

chore: upgrade plugins using vertx4

---

release.json

chore: prepare release.json for release 3.9.3

---

release.json

chore: prepare release for gravitee-definition

---

release.json

feat(xml): add xml support

---

release.json

feat(resource-cache): update api-cache-provider version

---

release.json

fix: upgrade version for tcp & file reporters

---

release.json

https://github.com/gravitee-io/issues/issues/1581

feat: add support for tracing

---

release.json

and prepare next 3.5.x release

Move management api in monorepo 3.5.x

---

release.json

chore: gateway need api-management to be built

---

upgrades/3.x/3.11.0/README.adoc
upgrades/3.x/README.adoc

docs: add breaking change information due to monorepo

---

release.json

fix: threat protection policies: unable to adjust default values

---

upgrades/3.x/3.9.4/README.adoc
upgrades/3.x/README.adoc

docs: threat protection policies: unable to adjust default values

---

release.json

Closes gravitee-io/issues#6050

chore: bump json-threat policy to properly check array size

---

release.json

Closes gravitee-io/issues#6051

fix(el): reintroduce request.method access

---

upgrades/3.x/3.12.0/README.adoc
upgrades/3.x/README.adoc

docs: announce change on default value for bridge service

---

release.json

chore: update json & xml threat-protection policies to embed 5982 fixes

---

release.json

feat: allow access to SSL attributes in EL TemplateEngine

---

release.json

chore: bump gravitee-expression-language to 1.5.1-SNAPSHOT

---

release.json

feat: create generate http signature policy

---

upgrades/3.x/3.10.1/README.adoc
upgrades/3.x/3.11.1/README.adoc
upgrades/3.x/3.11.1/mongodb/1-event-debug-migration.js
upgrades/3.x/README.adoc

refactor(debug): migrate sync implementation

---

upgrades/3.x/3.11.1/README.adoc
upgrades/3.x/3.11.1/mongodb/1-event-debug-migration.js
upgrades/3.x/README.adoc

refactor(debug): use simple events search instead of searchLatest

---

release.json
upgrades/3.x/3.12.0/README.adoc
upgrades/3.x/3.12.0/mongodb/api-keys-migration.js

https://github.com/gravitee-io/issues/issues/6005
**WARN : do not merge this issue before step2 is done (https://github.com/gravitee-io/issues/issues/6006)
(you can actually review it and test non regression) I'll PR step2 branch into this one**

docs: add 3.12.0 upgrade note with ApiKey migration script for mongoDB 

---

release.json

fix: node stop event not well propagated

---

release.json

chore: add management webui to apim monorepo - master

---

release.json

https://github.com/gravitee-io/issues/issues/6306

chore: bump gravitee-common and gravitee-node versions

---

release.json

chore: bump expression language version

---

release.json

fix(reporter): resolve ES monitor reporters

---

release.json

fix(reporter): resolve Kafka monitor reporters

---

upgrades/3.x/3.13.0/README.adoc
upgrades/3.x/README.adoc

docs: announce bridge http server disabling by default

---

upgrades/3.x/3.13.0/README.adoc

⚠️ Wait for the 3.13.0 release before merging this PR ⚠️
gravitee-io/issues#6145

doc: add breaking change info about UIs migration into monorepo

---

upgrades/3.x/3.13.0/README.adoc

⚠️ Wait for the 3.13.0 release before merging this PR ⚠️
gravitee-io/issues#6146

Add breaking change info regarding portal in monorepo

---

release.json

fix(logs): append headers/payload to client response

---

release.json

Related to https://github.com/gravitee-io/issues/issues/6574

chore: update gravitee-gateway-api

---

release.json

chore: merge gateway into monorepo - 3.5.x

---

release.json

chore: merge gateway into monorepo - 3.10.x

---

release.json

chore: merge gateway into monorepo - 3.12.x

---

release.json

chore: merge gateway into monorepo - 3.13.x

---

release.json

chore: merge gateway into monorepo

---

upgrades/3.x/3.5.25/README.adoc
upgrades/3.x/README.adoc

Zip files and folders have been renamed
gravitee-io/issues#6633
⚠️ wait for the 3.5.25 to be released before merging this PR ⚠️

doc: gateway has been merged in APIM monorepo

---

upgrades/3.x/3.10.8/README.adoc

https://github.com/gravitee-io/issues/issues/6586
⚠️ Wait for 3.10.8 release before merging this PR ⚠️

docs: add 3.10.8 upgrade note, explaining plans data fix process

---

release.json

chore: prepare 3.5.26 and bump policy-retry

---

release.json

feat: release gravitee-common & gravitee-node

---

release.json

fix: bump gravitee-definition to 1.30.1

---

release.json

prepare next patch version

---

release.json

**Issue**
https://github.com/gravitee-io/issues/issues/6707

chore: bump gravitee-policy-retry to 2.0.0

---

release.json

fix: bump gravitee-definition version

---

upgrades/3.x/3.14.0/README.adoc

https://github.com/gravitee-io/issues/issues/6683
⚠️ Wait 3.12.5 to be released before merge ⚠️

docs: add 3.14.0 upgrade note about ElasticSearch reporter plugins configuration change

---

release.json

fix: gravitee-policy-json-to-json

---

release.json

update version of all project for 3.15

---

release.json

bump gravitee-node version

---

release.json

fix: upgrade cache policy

---

upgrades/3.x/3.10.11/README.adoc

**Issue**
https://github.com/gravitee-io/issues/issues/7138
https://github.com/gravitee-io/issues/issues/7143

docs(3.10.11): add breaking change regarding platform policies

---

upgrades/3.x/3.10.11/README.adoc

docs: add a note on liquibase execution at GW startup

---

upgrades/3.x/3.16.0/README.adoc
upgrades/3.x/README.adoc

https://github.com/gravitee-io/issues/issues/7003
https://github.com/gravitee-io/issues/issues/7013

docs: add 3.16.0 upgrade note for import process

---

release.json

chore: bump gateway-api & expression-language

---

release.json

https://github.com/gravitee-io/issues/issues/7130

chore: bump version of jws, jsontojson, jsontoxml, xmltojson, xslt policies

---

release.json

feat(debug): view call metrics

---

release.json

chore: bump groovy-policy version

---

release.json

chore: bump gravitee-expression-language

---

release.json

https://github.com/gravitee-io/issues/issues/7333

chore: bump transform-headers policy to 1.10.0

---

release.json

https://github.com/gravitee-io/issues/issues/7301

chore: bump xml-thread 1.3.1, json-threat 1.3.2, json-validation 1.6.1

---

release.json

https://github.com/gravitee-io/issues/issues/7301

chore: bump xml-threat 1.2.2, json-threat 1.2.3, json-validation 1.6.1

---

release.json

https://github.com/gravitee-io/issues/issues/7405

chore: bump http-connector to 1.1.3

---

release.json

https://github.com/gravitee-io/issues/issues/7441

chore: prepare next version (3.16.3)

---

README.md

see https://github.com/gravitee-io/issues/issues/7041

doc: add note about new mongodb upgrade scripts location

---

release.json

Adapt release.json with gravitee-elasticsearch split - 3.17.x

---

release.json

https://github.com/gravitee-io/issues/issues/7783

Merge 3.15.9 into 3.16.x 

---

release.json

chore: bump openif userinfo to 1.5.1
